=== Erickjhoel/segundotrimestre/XML/public_html/XML/ZanalCar/newXmlSchemaZanalCar.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    
    <xs:element name="ZanalCar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Vehiculos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Coche" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Color" type="xs:string" />
                                        <xs:element name="Marca" type="xs:string" />
                                        <xs:element name="PrecioCompra" type="xs:integer" />
                                        <xs:element name="PrecioVenta" type="xs:integer" />
                                        <xs:element name="Matricula" type="xs:string" />
                                        <xs:element name="KilometrosUso" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Moto" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Color" type="xs:string" />
                                        <xs:element name="Marca" type="xs:string" />
                                        <xs:element name="PrecioCompra" type="xs:integer" />
                                        <xs:element name="PrecioVenta" type="xs:integer" />
                                        <xs:element name="Matricula" type="xs:string" />
                                        <xs:element name="KilometrosUso" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Bici" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Color" type="xs:string" />
                                        <xs:element name="Marca" type="xs:string" />
                                        <xs:element name="PrecioCompra" type="xs:integer" />
                                        <xs:element name="PrecioVenta" type="xs:integer" />
                                        <xs:element name="TamaÃ±oRueda" type="xs:integer" />
                                        <xs:element name="NumeroCambios" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Quad" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Color" type="xs:string" />
                                        <xs:element name="Marca" type="xs:string" />
                                        <xs:element name="PrecioCompra" type="xs:integer" />
                                        <xs:element name="PrecioVenta" type="xs:integer" />
                                        <xs:element name="Matricula" type="xs:string" />
                                        <xs:element name="KilometrosUso" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== Erickjhoel/segundotrimestre/XML/public_html/XML/ZanalCar/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ZanalCar
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/daw/NetBeansProjects/segundotrimestre/XML/public_html/XML/ZanalCar/newXmlSchemaZanalCar.xsd'>
    <Vehiculos>
        <Coche>
            <Color></Color>
            <Marca></Marca>
            <PrecioCompra>5</PrecioCompra>
            <PrecioVenta>6</PrecioVenta>
            <Matricula></Matricula>
            <KilometrosUso>3</KilometrosUso>
        </Coche>
        <Moto>
            <Color></Color>
            <Marca></Marca>
            <PrecioCompra>6</PrecioCompra>
            <PrecioVenta>6</PrecioVenta>
            <Matricula></Matricula>
            <KilometrosUso>6</KilometrosUso>
        </Moto>
        
        <Bici>
            <Color></Color>
            <Marca></Marca>
            <PrecioCompra>6</PrecioCompra>
            <PrecioVenta>6</PrecioVenta>
            <TamañoRueda>6</TamañoRueda>
            <NumeroCambios>6</NumeroCambios>
        </Bici>
        <Quad>
            <Color></Color>
            <Marca></Marca>
            <PrecioCompra>6</PrecioCompra>
            <PrecioVenta>6</PrecioVenta>
            <Matricula></Matricula>
            <KilometrosUso>6</KilometrosUso>
        </Quad>
    </Vehiculos>

</ZanalCar>
