=== Erickjhoel/segundotrimestre/XML/public_html/XML/Polideportivo/newXmlSchemaPolideportivo.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="Polideportivo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Alumnos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Alumno" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nombre" type="xs:string" />
                                        <xs:element name="Apellido" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Actividades">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Actividad">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Aerobic" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="NumeroDePlazas" type="xs:integer"/>
                                                    <xs:element name="PrecioActividad" type="xs:integer"/>
                                                    <xs:element name="Horario" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                            
                                        <xs:element name="ArtesMarciales" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="NumeroDePlazas" type="xs:integer"/>
                                                    <xs:element name="PrecioActividad" type="xs:integer"/>
                                                    <xs:element name="Horario" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                            
                                        <xs:element name="Natacion" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="NumeroDePlazas" type="xs:integer"/>
                                                    <xs:element name="PrecioActividad" type="xs:integer"/>
                                                    <xs:element name="Horario" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                            
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
        
            
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Erickjhoel/segundotrimestre/XML/public_html/XML/Polideportivo/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<Polideportivo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/daw/NetBeansProjects/segundotrimestre/XML/public_html/XML/Polideportivo/newXmlSchemaPolideportivo.xsd'>
    <Alumnos>
        <Alumno>
            <Nombre></Nombre>
            <Apellido></Apellido>
        </Alumno>
    </Alumnos>
    <Actividades>
        <Actividad>
            <Aerobic>
                <NumeroDePlazas>3</NumeroDePlazas>
                <PrecioActividad>3</PrecioActividad>
                <Horario></Horario>
            </Aerobic>
            <ArtesMarciales>
                <NumeroDePlazas>6</NumeroDePlazas>
                <PrecioActividad>6</PrecioActividad>
                <Horario></Horario>
            </ArtesMarciales>
            <Natacion>
                <NumeroDePlazas>6</NumeroDePlazas>
                <PrecioActividad>6</PrecioActividad>
                <Horario></Horario>
            </Natacion>
        </Actividad>
    </Actividades>

</Polideportivo>
