=== Erickjhoel/segundotrimestre/XML/public_html/XML/Merchadona/newXmlSchemaMerchadona.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="Merchadona">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Empleados">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Cajero" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nombre" type="xs:string" />
                                        <xs:element name="ID" type="xs:integer" />
                                        <xs:element name="NumeroProductosVendidos" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Reponedor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nombre" type="xs:string" />
                                        <xs:element name="ID" type="xs:integer" />
                                        <xs:element name="NumeroProductosRepuestos" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Perecedero" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="FechaDeReposicion" type="xs:string" />
                                        <xs:element name="PrecioProducto" type="xs:integer" />
                                        <xs:element name="NombreProducto" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="NoPerecedero" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="NombreProducto" type="xs:string" />
                                        <xs:element name="PrecioProducto" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                
                
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    
    
    
    
</xs:schema>

=== Erickjhoel/segundotrimestre/XML/public_html/XML/Merchadona/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<Merchadona
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/daw/NetBeansProjects/segundotrimestre/XML/public_html/XML/Merchadona/newXmlSchemaMerchadona.xsd'>
    <Empleados>
        <Cajero>
            <Nombre></Nombre>
            <ID>3</ID>
            <NumeroProductosVendidos>8</NumeroProductosVendidos>
        </Cajero>
        <Reponedor>
            <Nombre></Nombre>
            <ID>3</ID>
            <NumeroProductosRepuestos>3</NumeroProductosRepuestos>
        </Reponedor>
    </Empleados>
    <Productos>
        <Perecedero>
            <FechaDeReposicion></FechaDeReposicion>
            <PrecioProducto>9</PrecioProducto>
            <NombreProducto></NombreProducto>
        </Perecedero>
        <NoPerecedero>
            <NombreProducto></NombreProducto>
            <PrecioProducto>3</PrecioProducto>
        </NoPerecedero>
    </Productos>

</Merchadona>

=== Erickjhoel/segundotrimestre/XSL/public_html/xml/Merchadona.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<Merchadona
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/daw/NetBeansProjects/segundotrimestre/XML/public_html/XML/Merchadona/newXmlSchemaMerchadona.xsd'>
    <Empleados>
        <Cajero>
            <Nombre>RONY</Nombre>
            <ID>3</ID>
            <NumeroProductosVendidos>8</NumeroProductosVendidos>
        </Cajero>
        <Reponedor>
            <Nombre>PATRICIO</Nombre>
            <ID>5</ID>
            <NumeroProductosRepuestos>3</NumeroProductosRepuestos>
        </Reponedor>
    </Empleados>
    <Productos>
        <Perecedero>
            <FechaDeReposicion>25/01/199</FechaDeReposicion>
            <PrecioProducto>9</PrecioProducto>
            <NombreProducto>colita</NombreProducto>
        </Perecedero>
        <NoPerecedero>
            <NombreProducto>toto</NombreProducto>
            <PrecioProducto>3</PrecioProducto>
        </NoPerecedero>
    </Productos>

</Merchadona>
